version: 2.1
executors:
  default:
    working_directory: ~/ec2_sample
    docker:
      - image: ruby:2.6.3-stretch
        environment:
          BUNDLE_GEMFILE: /root/ec2_sample/Gemfile
          BUNDLE_PATH: /root/ec2_sample/vendor/bundle/ruby/2.6.3
jobs:
  checkout-code:
    executor:
      name: default
    steps:
      - checkout
      - restore_cache:
          keys:
            - gf-bundle-1-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gf-bundle-1-{{ .Branch }}-
            - gf-bundle-1-
      - run:
          name: bundler install
          command: gem install bundler:2.0.1
      - run:
          name: Bundle install
          command: bundle install --path=./vendor/bundle
      - save_cache:
          key: gf-bundle-1-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle
      - persist_to_workspace:
          root: .
          paths: .
  hoge-job:
    executor:
      name: default
    steps:
      - attach_workspace:
          at: ~/ec2_sample
      - run:
          name: hoge ruby
          command: bundle exec ruby hoge.rb
      - persist_to_workspace:
          root: .
          paths: .
  run-command:
    executor:
      name: default
    steps:
      - attach_workspace:
          at: ~/ec2_sample
      - run:
          name: hoge ruby
          command: bundle exec ruby ec2_run_command.rb

workflows:
  ec2-ci:
    jobs:
      - checkout-code
      - hoge-job:
          requires:
            - checkout-code
      - run-command:
          requires:
            - hoge-job
